AirportCarpool/AirportCarpool/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirportCarpool.Models;
using AirportCarpool.Services;
using WebMatrix.WebData;

namespace AirportCarpool.Controllers {
    public class TripController : Controller {

        public ActionResult NewTrip() {
            return View("NewTrip01", new NewTrip());
        }

        [HttpPost]
        public ActionResult NewTrip(NewTrip newTrip) {
            var view = HttpContext.Request["View"];
            switch (view) {
                case "NewTrip01":
                    var locationFrom = newTrip.LocationFrom;
                    var locationTo = newTrip.LocationTo;

                    var valid = ModelState.IsValid;

                    if (locationFrom == locationTo) {
                        ModelState.AddModelError("LocationTo", string.Format("The location to ({0}) must be different from the location from ({1}).", locationTo, locationFrom));
                        valid = false;
                    }
                    if (valid) {
                        SearchFlights(newTrip);
                        return View("NewTrip02", newTrip);
                    }

                    // Invalid:
                    return View("NewTrip01", newTrip);
                case "NewTrip02":
                    if (newTrip.FlightNumber != "") {
                        return View("NewTrip03", newTrip);
                    }
                    SearchFlights(newTrip);
                    return View("NewTrip02", newTrip);
                case "NewTrip03":
                    valid = ModelState.IsValid;
                    if (!newTrip.Driver && !newTrip.Passenger) {
                        ModelState.AddModelError("Passenger", "Please choose at least one of these options.");
                        valid = false;
                    }
                    if (valid) {
                        if (newTrip.Driver) {
                            return View("NewTrip04", newTrip);
                        } else {
                            var movement = SaveNewTrip(newTrip);
                            return RedirectToAction("FindCarpoolsByDate", "Carpool", new { movementId = movement.MovementId });
                        }
                    }
                    return View("NewTrip03", newTrip);
                case "NewTrip04":
                    if (ModelState.IsValid) {
                        var movement = SaveNewTrip(newTrip);
                        return RedirectToAction("FindCarpoolsByDate", "Carpool", new { movementId = movement.MovementId });
                    }
                    return View("NewTrip04", newTrip);

            }
            // Unknown:
            return View(view, newTrip);
        }

        private void SearchFlights(NewTrip newTrip) {
            var locationFrom = newTrip.LocationFrom;
            var locationTo = newTrip.LocationTo;
            FlightService flightService = new FlightService();
            List<Flight> flights = flightService.SearchFlights(newTrip.MovementDate);
            List<Flight> remove = new List<Flight>();
            foreach (var flight in flights) {
                if ((locationFrom == "Schiphol" && flight.ArrDep == "D") || (locationTo == "Schiphol" && flight.ArrDep == "A")) {
                    remove.Add(flight);
                } else {
                    TimeSpan flightTime;
                    TimeSpan minimum;
                    TimeSpan maximum;
                    if (flight.ArrDep == "A") {
                        flightTime = flight.Arrival.TimeOfDay;
                        minimum = newTrip.MovementTime.AddHours(-1).TimeOfDay;
                        maximum = newTrip.MovementTime.AddHours(1).TimeOfDay;
                    } else {
                        flightTime = flight.Departure.TimeOfDay;
                        minimum = newTrip.MovementTime.AddHours(1).TimeOfDay;
                        maximum = newTrip.MovementTime.AddHours(3).TimeOfDay;
                    }
                    if (flightTime < minimum || flightTime > maximum) {
                        remove.Add(flight);
                    }
                }
            }
            foreach (var flight in remove) {
                flights.Remove(flight);
            }
            ViewBag.ListFlights = flights;
        }

        private Movement SaveNewTrip(NewTrip newTrip) {
            var movement = new Movement();
            var db = new AirportCarpoolDbContext();
            db.Entry(movement).State = EntityState.Added;

            var user = GetUserByUserName(db, WebSecurity.CurrentUserName);
            db.Entry(user).State = EntityState.Unchanged;

            movement.User = user;
            Location locationFrom = null;
            if (newTrip.LocationFrom == "Home" && user.Location != null) {
                locationFrom = Location.GetCopy(user.Location);
            } else if (newTrip.LocationFrom == "Schiphol") {
                locationFrom = Location.GetNewSchipholLocation();
            }
            if (locationFrom != null) {
                db.Entry(locationFrom).State = EntityState.Added;
            }
            movement.LocationFrom = locationFrom;

            Location locationTo = null;
            if (newTrip.LocationTo == "Home" && user.Location != null) {
                locationTo = Location.GetCopy(user.Location);
            } else if (newTrip.LocationTo == "Schiphol") {
                locationTo = Location.GetNewSchipholLocation();
            }
            if (locationTo != null) {
                db.Entry(locationTo).State = EntityState.Added;
            }
            movement.LocationTo = locationTo;

            movement.Driver = newTrip.Driver;
            movement.Passenger = newTrip.Passenger;
            movement.Seats = newTrip.Seats;
            movement.Luggage = newTrip.Luggage;
            if (newTrip.Driver) {
                movement.MaxSeats = newTrip.MaxSeats;
                movement.MaxLuggage = newTrip.MaxLuggage;
                movement.MaxKm = newTrip.MaxKm;
            }
            movement.MovementDateTime = newTrip.MovementDate.Add(newTrip.MovementTime.TimeOfDay);
            movement.MovementDateType = newTrip.MovementDateType;

            if (movement.Driver) {
                var carpool = new Carpool();
                carpool.Status = CarpoolStatus.New;
                carpool.MaxKm = newTrip.MaxKm;
                carpool.MaxSeats = newTrip.MaxSeats;
                carpool.MaxLuggage = newTrip.MaxLuggage;
                carpool.Arrival = movement.MovementDateTime;
                db.Entry(carpool).State = EntityState.Added;
                carpool.Movements = new List<Movement>();
                carpool.Movements.Add(movement);
            }

            db.SaveChanges();
            db.Dispose();

            if (newTrip.FlightNumber != "") {
                db = new AirportCarpoolDbContext();
                Flight flight = new Flight {
                    FlightNumber = newTrip.FlightNumber,
                    ArrDep = newTrip.ArrDep,
                    Arrival = newTrip.Arrival,
                    Departure = newTrip.Departure,
                    Date = newTrip.MovementDate,
                    MovementId = movement.MovementId
                };
                db.Entry(flight).State = EntityState.Added;
                db.SaveChanges();
                db.Dispose();
            }

            

            return movement;
        }

        private User GetUserByUserName(AirportCarpoolDbContext db, string userName) {
            return (from u in db.Users
                    where u.UserName == userName
                    select u).SingleOrDefault<User>();
        }
    }
}

AirportCarpool/AirportCarpool/Views/Trip/NewTrip01.cshtml
@model AirportCarpool.Models.NewTrip

@{
    ViewBag.Title = "New trip";
}


@using (Html.BeginForm("NewTrip", "Trip", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <input type="hidden" name="View" value="NewTrip01" />
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="col-md-10">
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <legend>From</legend>
                    <input type="radio" id="LocationFrom1" name="LocationFrom" value="Home" checked />
                    <label for="LocationFrom1">Home</label>
                    <input type="radio" id="LocationFrom2" name="LocationFrom" value="Schiphol" />
                    <label for="LocationFrom2">Schiphol Airport</label>
                </fieldset>
                @Html.ValidationMessageFor(model => model.LocationFrom)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <legend>To</legend>
                    <input type="radio" id="LocationTo1" name="LocationTo" value="Home" />
                    <label for="LocationTo1">Home</label>
                    <input type="radio" id="LocationTo2" name="LocationTo" value="Schiphol" checked />
                    <label for="LocationTo2">Schiphol Airport</label>
                </fieldset>
                @Html.ValidationMessageFor(model => model.LocationTo)
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-10">
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <legend>Date and time to...</legend>
                    <input type="radio" id="MovementDateType1" name="MovementDateType" value="Arrive" checked />
                    <label for="MovementDateType1">Arrive</label>
                    <input type="radio" id="MovementDateType2" name="MovementDateType" value="Depart" />
                    <label for="MovementDateType2">Depart</label>
                </fieldset>
                @Html.ValidationMessageFor(model => model.MovementDateType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovementDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovementDate)
                @Html.ValidationMessageFor(model => model.MovementDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovementTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovementTime)
                @Html.ValidationMessageFor(model => model.MovementTime)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

AirportCarpool/AirportCarpool/Views/Trip/NewTrip02.cshtml
@model AirportCarpool.Models.NewTrip

@{
    ViewBag.Title = "New trip - choose your flight";
}

@using (Html.BeginForm("NewTrip", "Trip", FormMethod.Post, new { @id = "SelectFlightForm" })) {
    @Html.AntiForgeryToken()

    <input type="hidden" name="View" value="NewTrip02" />
    @Html.HiddenFor(model => model.LocationFrom);
    @Html.HiddenFor(model => model.LocationTo);
    @Html.HiddenFor(model => model.MovementDateType);
    @Html.HiddenFor(model => model.MovementDate);
    @Html.HiddenFor(model => model.MovementTime);
    <input type="hidden" name="FlightNumber" id="FlightNumber" value="" />
    <input type="hidden" name="Departure" id="Departure" value="" />
    <input type="hidden" name="Arrival" id="Arrival" value="" />
    <input type="hidden" name="ArrDep" id="ArrDep" value="" />

    <ul data-role="listview" data-theme="c" data-filter="true">

        @foreach (AirportCarpool.Models.Flight item in ViewBag.ListFlights) {   
            <li data-icon="arrow-r" data-iconpos="r">
                @Html.ActionLink(item.Summary(), "NewTrip", "Trip", null, new {
                    @class = "SelectFlightLink",
                    @data_flightnr = item.FlightNumber,
                    @data_departure = item.Departure,
                    @data_arrival = item.Arrival,
                    @data_arrdep = item.ArrDep
           })
            </li>   
        }
    </ul>
}

AirportCarpool/AirportCarpool/Views/Trip/NewTrip03.cshtml
@model AirportCarpool.Models.NewTrip

@{
    ViewBag.Title = "New trip";
}


@using (Html.BeginForm("NewTrip", "Trip", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <input type="hidden" name="View" value="NewTrip03" />
    @Html.HiddenFor(model => model.LocationFrom);
    @Html.HiddenFor(model => model.LocationTo);
    @Html.HiddenFor(model => model.MovementDateType);
    @Html.HiddenFor(model => model.MovementDate);
    @Html.HiddenFor(model => model.MovementTime);
    @Html.HiddenFor(model => model.FlightNumber);
    <input type="hidden" name="Departure" value="@Html.Raw(Model.Departure)">
    <input type="hidden" name="Arrival" value="@Html.Raw(Model.Arrival)">
    @Html.HiddenFor(model => model.ArrDep);
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Driver, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Driver)
                @Html.ValidationMessageFor(model => model.Driver)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Passenger, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Passenger)
                @Html.ValidationMessageFor(model => model.Passenger)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seats, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seats)
                @Html.ValidationMessageFor(model => model.Seats)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luggage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luggage)
                @Html.ValidationMessageFor(model => model.Luggage)
            </div>
        </div>

        <p>
            <input type="submit" value="Submit" />
        </p>
    </div>
}

AirportCarpool/AirportCarpool/Views/Trip/NewTrip04.cshtml
@model AirportCarpool.Models.NewTrip

@{
    ViewBag.Title = "New trip - driver options";
}


@using (Html.BeginForm("NewTrip", "Trip", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <input type="hidden" name="View" value="NewTrip04" />
    @Html.HiddenFor(model => model.LocationFrom);
    @Html.HiddenFor(model => model.LocationTo);
    @Html.HiddenFor(model => model.MovementDateType);
    @Html.HiddenFor(model => model.MovementDate);
    @Html.HiddenFor(model => model.MovementTime);
    @Html.HiddenFor(model => model.FlightNumber);
    <input type="hidden" name="Departure" value="@Html.Raw(Model.Departure)">
    <input type="hidden" name="Arrival" value="@Html.Raw(Model.Arrival)">
    @Html.HiddenFor(model => model.ArrDep);
    @Html.HiddenFor(model => model.Driver);
    @Html.HiddenFor(model => model.Passenger);
    @Html.HiddenFor(model => model.Seats);
    @Html.HiddenFor(model => model.Luggage);
    
    <div class="form-horizontal">
        <h3>Driver options</h3>
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaxSeats, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxSeats)
                @Html.ValidationMessageFor(model => model.MaxSeats)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxLuggage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxLuggage)
                @Html.ValidationMessageFor(model => model.MaxLuggage)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxKm, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxKm)
                @Html.ValidationMessageFor(model => model.MaxKm)
            </div>
        </div>

        <p>
            <input type="submit" value="Submit" />           
        </p>
    </div>
}